name: solarbextrapolation-rtd
channels:
  - conda-forge
dependencies:
  - python=3
  - astropy
  - numpy=1.12
  - matplotlib
  - mayavi
  - mock
  - scipy
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - sunpy
  - pip:
    - sunpy-sphinx-theme
