# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language: c

env:
    global:
        - TARGET_ARCH="x64"
        - CONDA_INSTALL_LOCN="${HOME}/conda"
    matrix:
        - CONDA_PY=2.7  CONDA_NPY=1.9

install:
    - python ./Obvious-CI/bootstrap-obvious-ci-and-miniconda.py ${CONDA_INSTALL_LOCN} ${TARGET_ARCH} ${CONDA_PY::1} --without-obvci
    - source ${CONDA_INSTALL_LOCN}/bin/activate root
    - conda config --set always_yes true
    - conda update conda
    - conda config --add channels sunpy --add channels astropy-ci-extras --add channels https://conda.binstar.org/sunpy/channel/citesting
    - conda create -n testing python=$CONDA_PY numpy=$CONDA_NPY && source activate testing
    - conda install sunpy mayavi

script:
    - # Update the conda recipe's meta.yaml with an appropriate version.
    - python setup.py test
    - echo "What?!"

