# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language: c
sudo: false
env:
  global:
    - PYTHON_VERSION=2.7
    - NUMPY_VERSION='stable'
    - ASTROPY_VERSION='stable'
    - MAIN_CMD='python setup.py'
    - CONDA_DEPENDENCIES='scipy matplotlib pytest sunpy sphinx mayavi sphinx-gallery'
    - CONDA_CHANNELS='conda-forge'
    - NUMPY_VERSION='1.12'
    - SETUP_XVFB=True
  matrix:
    - SETUP_CMD='install'
    - SETUP_CMD='build_docs'
    - SETUP_CMD='test'
install:
  - git clone https://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_${TRAVIS_OS_NAME}.sh
script:
  - $MAIN_CMD $SETUP_CMD
